name: Dast Scanning

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'
  push:
    branches: [main]

jobs:
  # Job 1: DAST - Dynamic Application Security Testing (on staging)
  dast:
    name: DAST Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        continue-on-error: true
        with:
          target: 'https://storefront-medusashop-prod.azurewebsites.net'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          fail_action: false
          allow_issue_writing: false

      - name: SSL/TLS Security Check
        run: |
          echo "Checking SSL/TLS configuration..."
          curl -vI https://storefront-medusashop-prod.azurewebsites.net 2>&1 | grep -E "SSL|TLS|cipher"
          openssl s_client -connect storefront-medusashop-prod.azurewebsites.net:443 -servername storefront-medusashop-prod.azurewebsites.net < /dev/null 2>&1 | grep -E "Protocol|Cipher"
        continue-on-error: true
